# CHEAT-SHEET
#
# start container:
#   docker-compose up -d tds-dev
#
# stop container:
#   docker-compose stop tds-dev 
#
# remove container
#   docker-compose rm -f tds-dev
#
# login to container 
#   docker exec -it tds-dev bash
# 
# reload nginx without restarting
# docker exec nginx /etc/init.d/nginx reload

nginx:
  image: bradjonesllc/docker-nginx-letsencrypt
  ports: 
    - "80:80"
    - "443:443"
  container_name: nginx
  volumes:
    - /opt/docker/brad/dhparam:/etc/ssl/dhparam 
    - /opt/docker/brad/letsencrypt:/etc/letsencrypt 
    - /opt/docker/nginx/conf.d/brad.conf:/etc/nginx/conf.d/brad.conf
    - /opt/docker/nginx/conf.d/include/cors.include:/etc/nginx/conf.d/include/cors.include
  environment:
    - "CERTS=gamone.whoi.edu"
    - "EMAIL=rsignell@usgs.gov"

###
# tds-dev:  THREDDS Data Server- Development
###
tds-dev:
  image: unidata/thredds-docker:5.0-SNAPSHOT
  ports:
    - "8080:8080"
  container_name: tds-dev
  volumes:
    - /opt/docker/tds-dev/tomcat/logs/:/usr/local/tomcat/logs/
    - /opt/docker/tds-dev/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
    - /opt/docker/tds-dev/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /opt/docker/tds-dev/thredds/:/usr/local/tomcat/content/thredds
    - /usgs:/usgs:ro
    - /sand/usgs:/sand/usgs:ro
#    - /clay/usgs:/clay/usgs:ro


###
# pycsw: pycsw Production
###

pycsw:
  image: axiom/docker-pycsw
  ports:
    - "8000:8000"
  container_name: pycsw
  volumes:
    - /opt/docker/pycsw/usgs-cmg.cfg:/opt/pycsw/default.cfg
    - /opt/docker/pycsw/force:/force 
    - /opt/docker/pycsw/export:/export
    - /opt/docker/pycsw/store:/store
    - /opt/docker/pycsw/database:/database


###
# ncwms:  ncWMS standalone web service
###

ncwms:
  image: axiom/ncwms:simpledev
  ports:
    - "9090:8080"
  container_name: ncwms
  volumes:
    - /opt/docker/ncwms/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /opt/docker/ncwms/tomcat/content:/usr/local/tomcat/.ncWMS2
#   - /opt/docker/ncwms/ncWMS.xml:/usr/local/tomcat/conf/Catalina/localhost/ncWMS.xml
  environment: 
    - DEFAULT_PALETTE=x-Rainbow


###
# harvester:  thredds-iso-harvester
###

#daily-harvester:
#  image: axiom/thredds-iso-harvester
#  container_name: daily-harvester
#  volumes:
#    - /opt/docker/pycsw/harvest/harvest.py:/srv/daily-harvest.py
#    - /opt/docker/pycsw/force/iso_records:/srv/iso

###
# sci-wms:  python-based wms for ugrid, sgrid
###

sci-wms:
  image: axiom/sci-wms
  ports:
    - "7002:7002"
  environment: 
    - SCIWMS_USERNAME=admin
    - SCIWMS_PASSWORD=tailpp1
  container_name: sci-wms
  volumes:
    - /opt/docker/sci-wms/topology:/srv/sci-wms/wms/topology 
    - /opt/docker/sci-wms/db:/srv/sci-wms/sciwms/db

erddap:
  image: axiom/docker-erddap:1.74
  ports:
    - "8090:8080"
  container_name: erddap
  volumes:
    - /opt/docker/erddap/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml  
    - /opt/docker/erddap/setup.xml:/usr/local/tomcat/content/erddap/setup.xml  
    - /opt/docker/erddap/datasets.xml:/usr/local/tomcat/content/erddap/datasets.xml  
    - /opt/docker/erddap/data:/erddapData
    - /usgs:/usgs:ro
    - /sand:/sand:ro
